// <auto-generated />
using System;
using IntraProjects.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntraProjects.Infrastructure.Migrations
{
    [DbContext(typeof(IntraProjectsDbContext))]
    partial class IntraProjectsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntraProjects.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AdObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("AdObjectId")
                        .IsUnique();

                    b.HasIndex("SamAccountName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<int>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditEventId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CharterId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityDisplayId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditEventId");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CharterId");

                    b.HasIndex("EntityType", "EntityId", "ChangedAt");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.CharterStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StatusId");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("CharterStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            DisplayName = "Draft",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 1,
                            StatusCode = "Draft"
                        },
                        new
                        {
                            StatusId = 2,
                            DisplayName = "Active",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 2,
                            StatusCode = "Active"
                        },
                        new
                        {
                            StatusId = 3,
                            DisplayName = "On Hold",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 3,
                            StatusCode = "OnHold"
                        },
                        new
                        {
                            StatusId = 4,
                            DisplayName = "Completed",
                            IsActive = true,
                            IsTerminal = true,
                            SortOrder = 4,
                            StatusCode = "Completed"
                        },
                        new
                        {
                            StatusId = 5,
                            DisplayName = "Cancelled",
                            IsActive = true,
                            IsTerminal = true,
                            SortOrder = 5,
                            StatusCode = "Cancelled"
                        });
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.CharterStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CharterId")
                        .HasColumnType("int");

                    b.Property<int?>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("CharterId", "ChangedAt");

                    b.ToTable("CharterStatusHistories");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityId"));

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PriorityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PriorityId");

                    b.HasIndex("PriorityCode")
                        .IsUnique();

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            PriorityId = 1,
                            ColorHex = "#ef4444",
                            DisplayName = "Critical",
                            PriorityCode = "Critical",
                            SortOrder = 1
                        },
                        new
                        {
                            PriorityId = 2,
                            ColorHex = "#f97316",
                            DisplayName = "High",
                            PriorityCode = "High",
                            SortOrder = 2
                        },
                        new
                        {
                            PriorityId = 3,
                            ColorHex = "#eab308",
                            DisplayName = "Medium",
                            PriorityCode = "Medium",
                            SortOrder = 3
                        },
                        new
                        {
                            PriorityId = 4,
                            ColorHex = "#64748b",
                            DisplayName = "Low",
                            PriorityCode = "Low",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.ProjectCharter", b =>
                {
                    b.Property<int>("CharterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharterId"));

                    b.Property<DateOnly?>("ActualCloseDate")
                        .HasColumnType("date");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ArchivedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CharterNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApproach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("CharterId");

                    b.HasIndex("CharterNumber")
                        .IsUnique();

                    b.HasIndex("IsArchived");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TargetDate");

                    b.ToTable("ProjectCharters");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.ProjectTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("ApprovalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ArchivedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<int>("CharterId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentlyWaitingOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("NextStepSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryResourceLoad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectFolderDirectory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectObjectiveGoal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReminderDate")
                        .HasColumnType("date");

                    b.Property<string>("Requestor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReviewNeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("ScopeCreep")
                        .HasColumnType("bit");

                    b.Property<string>("SecondaryResourceLoad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondaryResourceUserId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StalledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StalledReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TaskNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("TravelNeeded")
                        .HasColumnType("bit");

                    b.Property<string>("Urgency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CharterId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TaskNumber")
                        .IsUnique();

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.ProjectTaskStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StatusId");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("ProjectTaskStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            DisplayName = "Open",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 1,
                            StatusCode = "Open"
                        },
                        new
                        {
                            StatusId = 2,
                            DisplayName = "In Progress",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 2,
                            StatusCode = "InProgress"
                        },
                        new
                        {
                            StatusId = 3,
                            DisplayName = "Stalled",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 3,
                            StatusCode = "Stalled"
                        },
                        new
                        {
                            StatusId = 4,
                            DisplayName = "Waiting on response",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 4,
                            StatusCode = "WaitingOn"
                        },
                        new
                        {
                            StatusId = 5,
                            DisplayName = "Under review",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 5,
                            StatusCode = "UnderReview"
                        },
                        new
                        {
                            StatusId = 6,
                            DisplayName = "Complete",
                            IsActive = true,
                            IsTerminal = true,
                            SortOrder = 6,
                            StatusCode = "Complete"
                        },
                        new
                        {
                            StatusId = 7,
                            DisplayName = "Cancelled",
                            IsActive = true,
                            IsTerminal = true,
                            SortOrder = 7,
                            StatusCode = "Cancelled"
                        });
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.Subtask", b =>
                {
                    b.Property<int>("SubtaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubtaskId"));

                    b.Property<string>("ApprovalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ArchivedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<int>("CharterId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentlyWaitingOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("NextStepSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryResourceLoad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectFolderDirectory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectObjectiveGoal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReminderDate")
                        .HasColumnType("date");

                    b.Property<string>("Requestor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReviewNeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("ScopeCreep")
                        .HasColumnType("bit");

                    b.Property<string>("SecondaryResourceLoad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondaryResourceUserId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StalledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StalledReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("SubtaskNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("TravelNeeded")
                        .HasColumnType("bit");

                    b.Property<string>("Urgency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubtaskId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CharterId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubtaskNumber")
                        .IsUnique();

                    b.HasIndex("TaskId");

                    b.ToTable("Subtasks");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.SubtaskStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StatusId");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("SubtaskStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            DisplayName = "Open",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 1,
                            StatusCode = "Open"
                        },
                        new
                        {
                            StatusId = 2,
                            DisplayName = "In Progress",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 2,
                            StatusCode = "InProgress"
                        },
                        new
                        {
                            StatusId = 3,
                            DisplayName = "Stalled",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 3,
                            StatusCode = "Stalled"
                        },
                        new
                        {
                            StatusId = 4,
                            DisplayName = "Waiting on response",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 4,
                            StatusCode = "WaitingOn"
                        },
                        new
                        {
                            StatusId = 5,
                            DisplayName = "Under review",
                            IsActive = true,
                            IsTerminal = false,
                            SortOrder = 5,
                            StatusCode = "UnderReview"
                        },
                        new
                        {
                            StatusId = 6,
                            DisplayName = "Complete",
                            IsActive = true,
                            IsTerminal = true,
                            SortOrder = 6,
                            StatusCode = "Complete"
                        },
                        new
                        {
                            StatusId = 7,
                            DisplayName = "Cancelled",
                            IsActive = true,
                            IsTerminal = true,
                            SortOrder = 7,
                            StatusCode = "Cancelled"
                        });
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("IntraProjects.Domain.Entities.AppUser", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntraProjects.Domain.Entities.ProjectCharter", "Charter")
                        .WithMany("AuditEvents")
                        .HasForeignKey("CharterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChangedBy");

                    b.Navigation("Charter");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.CharterStatusHistory", b =>
                {
                    b.HasOne("IntraProjects.Domain.Entities.ProjectCharter", "Charter")
                        .WithMany("StatusHistory")
                        .HasForeignKey("CharterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Charter");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.ProjectCharter", b =>
                {
                    b.HasOne("IntraProjects.Domain.Entities.AppUser", "Owner")
                        .WithMany("OwnedCharters")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntraProjects.Domain.Entities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntraProjects.Domain.Entities.CharterStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Priority");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.ProjectTask", b =>
                {
                    b.HasOne("IntraProjects.Domain.Entities.AppUser", "AssignedTo")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntraProjects.Domain.Entities.ProjectCharter", "Charter")
                        .WithMany("Tasks")
                        .HasForeignKey("CharterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntraProjects.Domain.Entities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntraProjects.Domain.Entities.ProjectTaskStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Charter");

                    b.Navigation("Priority");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.Subtask", b =>
                {
                    b.HasOne("IntraProjects.Domain.Entities.AppUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("IntraProjects.Domain.Entities.ProjectCharter", "Charter")
                        .WithMany()
                        .HasForeignKey("CharterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntraProjects.Domain.Entities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntraProjects.Domain.Entities.SubtaskStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntraProjects.Domain.Entities.ProjectTask", "Task")
                        .WithMany("Subtasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Charter");

                    b.Navigation("Priority");

                    b.Navigation("Status");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("OwnedCharters");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.ProjectCharter", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("StatusHistory");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("IntraProjects.Domain.Entities.ProjectTask", b =>
                {
                    b.Navigation("Subtasks");
                });
#pragma warning restore 612, 618
        }
    }
}
